### PR TITLE
Add a list of servers that players shouldnt log onto

### PR DESCRIPTION
**Pull request by QuanTrieuPCYT**
As the title said, we just want a "cleaner" and better Minecraft Vietnam Community <3

### CODE REVIEW

**Comment by TypicalShavonne** [comment]
upvote +1

**Comment by cart69420** [comment]
rat cang toi xin +1

**Comment by NeekoVN** [comment]
a +1

**Comment by minhh2792** [comment]
đoạn đầu tiên nói vậy mà ko có dẫn chứng dễ bị bash lắm
btw +1

**Comment by QuanTrieuPCYT** [comment]
made some commits so the repo will look cooler :sunglasses:

**Comment by minhquantommy** [comment]
+1 upvote

**Comment by QuanTrieuPCYT** [comment]
> +1 upvote

adu idol tommy vercetti

**Comment by Blender4k** [comment]
+1 up

**Comment by HSGamer** [comment]
This is a controversial topic.
If we apply this section to the main list, we should create a proper list of rules for a `server that players shouldnt log onto`.
We need to update the [CONTRIBUTING.md](https://github.com/HSGamer/list-of-shame-mcvn/blob/main/CONTRIBUTING.md) to make proper rules for this.

**Comment by Scarlaid** [comment]
+1, I'm just tired of seeing b.s Minecraft server being popular why some good ones are't

**Comment by vanh1104** [comment]
+1 :v

**Comment by HSGamer** [comment]
If someone have a idea for a draft of the rules to define `a bad server`, please create another PR. 
I and others will go to that PR to help making that the complete rules.

**Comment by HSGamer** [comment]
For those who want to discuss about this, I've created a post on Minecraftvn.net.
Link here: https://minecraftvn.net/list-of-shame-them-danh-sach-server-te-vao.t35969/

**Review by HSGamer — CHANGES_REQUESTED** [review]
Please add more evidences for your statements. Some of your statements are more like biases than complete statements. And biases may cause unnecessary issues with the object that is being shamed.

**Comment by HSGamer** [comment]
Since we do not allow bullying a particular object, I decided to close the PR here.
And I won't accept further PRs that "attack" a particular server.

**Comment by LongVN2k9** [comment]
> As the title said, we just want a "cleaner" and better Minecraft Vietnam Community <3

+1 adu circus + thicc xd

**Pull request closed without merging**
